<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>URL</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    <h1>URL</h1>
    <p>ID: ${url.id}</p>
    <p>URL: ${url.name}</p>
    <p>Дата создания: ${url.createdAt}</p>
</div>
</body>
</html>
