name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: build
          build-root-directory: app
      
      - run: cd app && ./gradlew checkstyleMain
      - run: cd app && ./gradlew test
      - run: cd app && ./gradlew jacocoTestReport

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: cd app && ./gradlew jacocoTestReport
          coverageLocations: ${{ github.workspace }}/app/build/reports/jacoco/test/jacocoTestReport.xml
          coverageInputType: jacoco
