name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: build jacocoTestReport
          build-root-directory: app

      - name: Run Checkstyle
        run: cd app && ./gradlew checkstyleMain

      - name: Run Tests
        run: cd app && ./gradlew test

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage
          path: app/build/reports/jacoco/test/html/
